# Generated by Django 4.1.4 on 2022-12-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
