# Generated by Django 4.1.4 on 2022-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='clip_to_upload',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
